server:
  port: 8090
  servlet:
    context-path: /api

jwt:
  secret: mztKH2Kgx0taIS7ZzPTh60559eCZ3HbK
  expiration: 86400000

spring:
  profiles:
    include: security
    active: ${API_ENV:development}